version: '2'
services:
    fiestasecurityui-app:
        image: fiestasecurityui
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fiestasecurityui-mysql:3306/fiestasecurityui?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JBOOTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fiestasecurityui-mysql:
        extends:
            file: mysql.yml
            service: fiestasecurityui-mysql
